// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/21/2025, 3:35:12 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/my_Projects/SpacetoonSongs/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/plugins/**/*.{js,ts,mjs}","E:/my_Projects/SpacetoonSongs/client/app/composables/**/*.{js,ts,mjs}","E:/my_Projects/SpacetoonSongs/client/app/utils/**/*.{js,ts,mjs}","E:/my_Projects/SpacetoonSongs/client/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;