// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/10/2025, 11:59:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["E:/my_Projects/SpacetoonSongs/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/plugins/**/*.{js,ts,mjs}","E:/my_Projects/SpacetoonSongs/client/app/composables/**/*.{js,ts,mjs}","E:/my_Projects/SpacetoonSongs/client/app/utils/**/*.{js,ts,mjs}","E:/my_Projects/SpacetoonSongs/client/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/my_Projects/SpacetoonSongs/client/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;